# Generated by Django 3.2.3 on 2021-08-24 00:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now=True, verbose_name="creado")),
                (
                    "modified",
                    models.DateTimeField(auto_now_add=True, verbose_name="modificado"),
                ),
                ("title", models.CharField(max_length=120, verbose_name="Titulo")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "assigned"), (2, "failed"), (3, "completed")],
                        verbose_name="Estatus",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignados",
                    ),
                ),
                (
                    "assignee_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assignee_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hits",
                        to="accounts.grouphitman",
                        verbose_name="Grupo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
